# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Recordings' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '4.0.0'
  pod 'RxDataSources', '3.0.2'

  target 'RecordingsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
